%\VignetteIndexEntry{Detection of De Novo Copy Number Variants from Illumina Genotyping Arrays}
%\VignetteDepends{}
%\VignetteKeywords{copy number, Illumina, SNP, genotype, high-throughput}
%\VignettePackage{MinimumDistance}

%%% The real .Rnw is under inst/scripts.
%%% It cannot be added here because it depends on external
%%% data not yet available as a BioC package
\documentclass{article}
\begin{document}
\end{document}