setGeneric("mindist", function(object) standardGeneric("mindist"))
setGeneric("mindist<-", function(object,value) standardGeneric("mindist<-"))
setGeneric("family", function(object) standardGeneric("family"))
setGeneric("plot", useAsDefault=function(x,y, ...) graphics::plot(x,y,...))
setGeneric("loglik", function(object) standardGeneric("loglik"))
setGeneric("loglik<-", function(object, value) standardGeneric("loglik<-"))
setGeneric("range.index", function(object) standardGeneric("range.index"))
setGeneric("calculateMindist", function(object, ..., verbose=TRUE) standardGeneric("calculateMindist"))
setGeneric("lrr<-", function(object, value) standardGeneric("lrr<-"))
setGeneric("baf<-", function(object, value) standardGeneric("baf<-"))
setGeneric("mad")
setGeneric("ncol")
setGeneric("mad<-", function(x, value) standardGeneric("mad<-"))
setGeneric("mad.sample", function(x) standardGeneric("mad.sample"))
setGeneric("mad.marker", function(x) standardGeneric("mad.marker"))
setGeneric("mad.sample<-", function(x, value) standardGeneric("mad.sample<-"))
setGeneric("mad.marker<-", function(x, value) standardGeneric("mad.marker<-"))
setGeneric("mad.mindist<-", function(x, value) standardGeneric("mad.mindist<-"))
setGeneric("mad.mindist", function(x) standardGeneric("mad.mindist"))
setGeneric("phenoData2", function(object) standardGeneric("phenoData2"))
setGeneric("phenoData2<-", function(object,value) standardGeneric("phenoData2<-"))
setGeneric("varLabels2", function(object) standardGeneric("varLabels2"))
setGeneric("prune", function(object, ranges, id,
			      lambda=0.05,
			      min.change=0.1,
			      min.coverage=3,
			      scale.exp=0.02,
			      verbose, ...)
	   standardGeneric("prune"))
setGeneric("computeBayesFactor", function(object,
					  ranges,
					  ...)
	   standardGeneric("computeBayesFactor"))
setGeneric("todf", function(object, rangeData, frame, ...) standardGeneric("todf"))
setGeneric("offspringNames", function(object) standardGeneric("offspringNames"))
setGeneric("offspringNames<-", function(object,value) standardGeneric("offspringNames<-"))
setGeneric("fatherNames", function(object) standardGeneric("fatherNames"))
setGeneric("fatherNames<-", function(object,value) standardGeneric("fatherNames<-"))
setGeneric("motherNames", function(object) standardGeneric("motherNames"))
setGeneric("motherNames<-", function(object,value) standardGeneric("motherNames<-"))
setGeneric("trioNames", function(object) standardGeneric("trioNames"))
setGeneric("rbind", function(..., deparse.level=1) standardGeneric("rbind"),
           signature = "...")
setGeneric("width", function(x) standardGeneric("width"))
setGeneric("sampleSheet", function(object) standardGeneric("sampleSheet"))
setGeneric("pedigree", function(object) standardGeneric("pedigree"))
setGeneric("allNames", function(object) standardGeneric("allNames"))
setGeneric("trios", function(object) standardGeneric("trios"))
setGeneric("minimumDistance", function(object, ...) standardGeneric("minimumDistance"))
setGeneric("trioplot", function(formula, object, range, ...) standardGeneric("trioplot"))
setGeneric("segment2", function(object, pos, chrom, id, ...) standardGeneric("segment2"))
setGeneric("mad2", function(object, byrow=FALSE, ...) standardGeneric("mad2"))
